// Code generated by mockery v2.40.1. DO NOT EDIT.

package mockinterfaces

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthMiddleware is an autogenerated mock type for the AuthMiddleware type
type MockAuthMiddleware struct {
	mock.Mock
}

type MockAuthMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthMiddleware) EXPECT() *MockAuthMiddleware_Expecter {
	return &MockAuthMiddleware_Expecter{mock: &_m.Mock}
}

// HandleAuthWithRole provides a mock function with given fields: roles
func (_m *MockAuthMiddleware) HandleAuthWithRole(roles ...string) gin.HandlerFunc {
	_va := make([]interface{}, len(roles))
	for _i := range roles {
		_va[_i] = roles[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HandleAuthWithRole")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(...string) gin.HandlerFunc); ok {
		r0 = rf(roles...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockAuthMiddleware_HandleAuthWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthWithRole'
type MockAuthMiddleware_HandleAuthWithRole_Call struct {
	*mock.Call
}

// HandleAuthWithRole is a helper method to define mock.On call
//   - roles ...string
func (_e *MockAuthMiddleware_Expecter) HandleAuthWithRole(roles ...interface{}) *MockAuthMiddleware_HandleAuthWithRole_Call {
	return &MockAuthMiddleware_HandleAuthWithRole_Call{Call: _e.mock.On("HandleAuthWithRole",
		append([]interface{}{}, roles...)...)}
}

func (_c *MockAuthMiddleware_HandleAuthWithRole_Call) Run(run func(roles ...string)) *MockAuthMiddleware_HandleAuthWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockAuthMiddleware_HandleAuthWithRole_Call) Return(_a0 gin.HandlerFunc) *MockAuthMiddleware_HandleAuthWithRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthMiddleware_HandleAuthWithRole_Call) RunAndReturn(run func(...string) gin.HandlerFunc) *MockAuthMiddleware_HandleAuthWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthMiddleware creates a new instance of MockAuthMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthMiddleware {
	mock := &MockAuthMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
