// Code generated by mockery v2.40.1. DO NOT EDIT.

package mockinterfaces

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockPaginationMiddleware is an autogenerated mock type for the PaginationMiddleware type
type MockPaginationMiddleware struct {
	mock.Mock
}

type MockPaginationMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaginationMiddleware) EXPECT() *MockPaginationMiddleware_Expecter {
	return &MockPaginationMiddleware_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields:
func (_m *MockPaginationMiddleware) Handle() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockPaginationMiddleware_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockPaginationMiddleware_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
func (_e *MockPaginationMiddleware_Expecter) Handle() *MockPaginationMiddleware_Handle_Call {
	return &MockPaginationMiddleware_Handle_Call{Call: _e.mock.On("Handle")}
}

func (_c *MockPaginationMiddleware_Handle_Call) Run(run func()) *MockPaginationMiddleware_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaginationMiddleware_Handle_Call) Return(_a0 gin.HandlerFunc) *MockPaginationMiddleware_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaginationMiddleware_Handle_Call) RunAndReturn(run func() gin.HandlerFunc) *MockPaginationMiddleware_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaginationMiddleware creates a new instance of MockPaginationMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaginationMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaginationMiddleware {
	mock := &MockPaginationMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
